Add invalid yaml detection for scans

diff --git a/.github/workflows/collector-reusable.yml b/.github/workflows/collector-reusable.yml
--- a/.github/workflows/collector-reusable.yml
+++ b/.github/workflows/collector-reusable.yml
@@ -240,10 +240,14 @@ jobs:
 
           done < images.txt
 
-          # Gate remains the same
           if grep -Eq 'HIGH|CRITICAL' scan-results/trivy-report.txt; then
             echo "Compliance failed: HIGH/CRITICAL vulnerabilities found."
             # exit 1
+          fi
+
+          if grep -Eq 'Fatal Error' scan-results/trivy-report.txt; then
+            echo "Compliance failed: Invalid yaml file for trivy."
+            exit 1
           fi
 
       # - name: Grype scan (gate)
